"""map auth rbac models

Revision ID: 6fa9eae0115b
Revises: 
Create Date: 2026-06-25 22:59:46.745036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fa9eae0115b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('permission_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('permission_id'),
    sa.UniqueConstraint('permission_code'),
    schema='auth'
    )
    op.create_table('roles',
    sa.Column('role_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    sa.UniqueConstraint('role_name'),
    schema='auth'
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    schema='auth'
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.role_id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    schema='auth'
    )
    op.create_table('user_permissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('permission_id', sa.BigInteger(), nullable=False),
    sa.Column('granted_by', sa.BigInteger(), nullable=True),
    sa.Column('justification', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['auth.users.user_id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['auth.permissions.permission_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['auth.roles.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='auth'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles', schema='auth')
    op.drop_table('user_permissions', schema='auth')
    op.drop_table('role_permissions', schema='auth')
    op.drop_table('users', schema='auth')
    op.drop_table('roles', schema='auth')
    op.drop_table('permissions', schema='auth')
    # ### end Alembic commands ###
